### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by naxmefy** [xwvvvvwx/typescript-react-electron-boilerplate#17]
If i clone and just execute the project (like readme says) i get the following error:

```
$ npm run server

> typescript-react-webpack@0.0.0 server /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate
> node dev-server.js

==> 🌎  Listening on port 3000. Open up http://localhost:3000/ in your browser.
TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/instance.ts:266:72)\n    at Object.ensureInstance (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/instance.ts:145:5)\n    at compiler (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at WEBPACK_CORE_LOADER_EXECUTION (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)\n    at runSyncOrAsync (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)\n    at nextLoader (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)\n    at /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5\n    at Storage.finished (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)\n    at /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)'
webpack built 5949515afe9855a86dda in 702ms
Hash: 5949515afe9855a86dda
Version: webpack 1.14.0
Time: 702ms
     Asset       Size  Chunks             Chunk Names
 bundle.js     102 kB       0  [emitted]  main
index.html  287 bytes          [emitted]
chunk    {0} bundle.js (main) 75.9 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 6.68 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [4] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [5] (webpack)-hot-middleware/client-overlay.js 1.74 kB {0} [built]
    [6] ./~/ansi-html/index.js 4.26 kB {0} [built]
    [7] ./~/html-entities/index.js 231 bytes {0} [built]
    [8] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
    [9] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
   [10] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
   [11] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
```

**some infos**
```
$ node -v
v6.9.4
$ npm -v
3.10.10
```

**Comment by MartinSGill** [comment]
Can be fixed by updating to newer version of awesome-typescript-loader.

Edit your dev dependencies section of package.json.

Version 3.0.0-beta.18 worked for me.

```
    "awesome-typescript-loader": "3.0.0-beta.18",
```

cf. https://github.com/s-panferov/awesome-typescript-loader/issues/293

**Comment by MartinSGill** [comment]
You'll also need to update the webpack config and remove the ForkCheckerPlugin references, as that's now bundled.

cf. https://github.com/s-panferov/awesome-typescript-loader/issues/274

**Comment by xwvvvvwx** [comment]
Thanks for the bug report! 👍

I'm not working with javascript at all right now, and I do not have the time (or inclination) to maintain a project that is of so little relevance to me.

Apologies if it causes any inconvenience, but I don't want to leave a dead project hanging around, so I will be removing the project from github.
