### ISSUE TITLE
app requires npm install too

### ISSUE THREAD

**Issue by naxmefy** [xwvvvvwx/typescript-react-electron-boilerplate#18]
Missing information in readme. If i clone the project and execute (like readme says) i get the following error

```
$ npm start

> typescript-react-webpack@0.0.0 start /Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate
> cross-env NODE_ENV=development electron app

App threw an error during load
Error: Cannot find module 'electron-squirrel-startup'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/naxmefy/github/naxmefy/typescript-react-electron-boilerplate/app/main.js:5:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Solution**:
```
$ cd app && npm i
```

**some infos**
```
$ node -v
v6.9.4
$ npm -v
3.10.10
```

**Comment by xwvvvvwx** [comment]
Thanks for the bug report! 👍 

I'm not working with javascript at all right now, and I do not have the time (or inclination) to maintain a project that is of so little relevance to me. 

Apologies if it causes any inconvenience, but I don't want to leave a dead project hanging around, so I will be removing the project from github.
